---
# tasks file for roles/nginx

- name: Show OS
  ansible.builtin.debug:
    var: ansible_distribution

- name: Install and configure Nginx
  block:
    - name: Install nginx only on ubuntu
      ansible.builtin.apt:
        name: "{{ nginx_package }}"
        state: present
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install Nginx
      ansible.builtin.apt:
        name: "{{ nginx_package }}"
        state: present
        update_cache: true

    - name: Ensure Nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
  rescue:
    - name: Log installation failure
      ansible.builtin.debug:
        msg: "Nginx installation or service start failed on {{ inventory_hostname }}"

  always:
    - name: Installation attempt completed
      ansible.builtin.debug:
        msg: "Nginx installation block completed on {{ inventory_hostname }}"

- name: Deploy dynamic webpage
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  notify: Restart nginx
